---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role
- name: Install nginx
  hosts: lighthouse
  handlers:
    - name: Start nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
    - name: Reload nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded
  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Start nginx
    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: Reload nginx
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role
