stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
image: cr.yandex/yc/metadata-token-docker-helper:0.2
services:
 - docker:19.03.1-dind
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - docker build . -t hello:gitlab-$CI_COMMIT_SHORT_SHA

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY/netology/example-netology/hello:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/netology/example-netology/hello:gitlab-$CI_COMMIT_SHORT_SHA

