apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynfs
spec:
  storageClassName: nfs-csi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi