---
all:
  hosts:
    sonar-01:
      ansible_host: 84.252.130.140
    nexus-01:
      ansible_host: 51.250.3.232
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology